apiVersion: "v1" 
kind: "Service"
metadata:
  labels:
    app: "zuul-api-gateway"
  name: "zuul-api-gateway"
spec:
  ports:
  - name: "http"
    port: 9999
    targetPort: 9999
    nodePort: 32470
  type: "NodePort"
  selector:
    app: "zuul-api-gateway"